import streamlit as st
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

st.set_page_config(page_title="Finance Policy RAG Dashboard", layout="wide")

st.title("Finance Policy RAG - Audit Dashboard")
st.markdown("Monitor the performance, escalation rates, and usage of the Finance Policy RAG Agent.")

# In a real scenario, this would load directly from Google Sheets API using a service account.
# For demonstration purposes in this portfolio piece, we generate mock data reflecting a typical week.
@st.cache_data
def load_mock_data():
    dates = [datetime.now() - timedelta(days=x) for x in range(14)]
    dates.reverse()
    
    questions = [
        "What is the travel advance limit?",
        "How many days to file reimbursement?",
        "Can I expense alcohol?",
        "What is the per diem rate for NYC?",
        "Do I need a receipt for a $15 coffee?",
        "How to book a flight?",
        "Maternity leave policy?",
        "Is home internet expensable?",
    ]
    
    data = []
    for d in dates:
        # Simulate varying volume
        num_questions = np.random.randint(5, 25)
        for _ in range(num_questions):
            q = np.random.choice(questions)
            # Simulate escalations (mostly for tricky questions)
            is_escalated = np.random.random() < 0.12 if "Maternity" not in q else np.random.random() < 0.6
            latency = np.random.normal(2.1, 0.4)
            
            data.append({
                "timestamp": d + timedelta(hours=np.random.randint(8, 18)),
                "question": q,
                "escalated": is_escalated,
                "latency_s": round(latency, 2)
            })
            
    return pd.DataFrame(data)

df = load_mock_data()

# Key Metrics
col1, col2, col3, col4 = st.columns(4)
col1.metric("Total Questions (14d)", len(df))
escalation_rate = (df['escalated'].sum() / len(df)) * 100
col2.metric("Escalation Rate", f"{escalation_rate:.1f}%")
col3.metric("Avg Latency", f"{df['latency_s'].mean():.2f}s")
col4.metric("Hit@3 Estimate", "84%")

st.divider()

# Charts
st.subheader("Trends")
col_chart1, col_chart2 = st.columns(2)

with col_chart1:
    st.markdown("**Questions per Day**")
    daily_counts = df.set_index('timestamp').resample('D').size()
    st.line_chart(daily_counts)

with col_chart2:
    st.markdown("**Escalation Rate per Day**")
    daily_escalations = df[df['escalated']].set_index('timestamp').resample('D').size()
    escalation_pct = (daily_escalations / daily_counts * 100).fillna(0)
    st.bar_chart(escalation_pct)

st.divider()

# Top Questions
st.subheader("Top Policy Questions")
st.markdown("Identify areas where the finance policy might need clarification based on employee queries.")
top_q = df['question'].value_counts().reset_index()
top_q.columns = ['Question', 'Count']
st.dataframe(top_q, use_container_width=True)

st.divider()
st.caption("Note: This dashboard visualizes the compliance and audit logs generated by the n8n RAG pipeline.")
